apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-stateful-pv
spec:
  storageClassName: statestorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data1
