apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql-deployment-webappdb
  labels:
    app: myapp 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata:
      name: myapp-mysql   
      labels: 
        app: mysql  
    spec: 
        containers:
          - name: mysql  
            image: mysql:5.6 
            env:
              - name: MYSQL_ROOT_PASSWORD 
                valueFrom:
                  secretKeyRef:
                    name: my-db-secret 
                    key: db-password
            ports:
              - containerPort: 3306 
                name: mysql 
            volumeMounts:
            - name: mysql-persistent-volume  
              mountPath: /var/lib/mysql
            - name: usermgmt-dbscript 
              mountPath: /docker-entrypoint-initdb.d 
        volumes:
          - name: mysql-persistent-volume 
            persistentVolumeClaim:
              claimName: new-task-pvc
          - name: usermgmt-dbscript
            configMap: 
              name: mytutorialwebapp-dbcreation-script
