apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      name: portfolio-pod 
      labels: 
        app: portfolio 
    spec:
      containers: 
        - name: portfolio-container 
          image: blazerrt86899/romu-portfolio 
          ports:
           - containerPort: 80
