apiVersion: v1 
kind: Pod
metadata:
  name: mem-allocation-quota-1
 
spec:
  containers:
  - name: mem-allocation-quota-ctd-1
    image: nginx 
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"
