apiVersion: v1 
kind: Pod
metadata:
  name: mem-allocation-quota
 
spec:
  containers:
  - name: mem-allocaiton-quota-ctd 
    image: nginx 
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
