apiVersion: apps/v1  
kind: Deployment 
metadata: 
  name: courseusermgmt-webapp
  labels:
    app: courseusermgmt-webapp
spec: 
  replicas: 1 
  selector:  
    matchLabels: 
      app: courseusermgmt-webapp
  
  template: 
    metadata:
      name: courseusermgmt-webapp   
      labels: 
        app: courseusermgmt-webapp   
    spec:
        containers:
          - name: courseusermgmt-webapp  
            image: blazerrt86899/courseusermgmt
            ports:
              - containerPort: 8080
                name: mysql 
            env:
              - name: DB_HOSTNAME
                value: 192.168.145.194
              - name: DB_PORT
                value: "3306"
              - name: DB_NAME 
                value: "webappdb"
              - name: DB_USERNAME
                value: "root"
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: user-db-secret 
                    key: db-password 
