apiVersion: v1
kind: PersistentVolume
metadata:
  name:  mgmt-task-pv
spec:
  storageClassName: nodestorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
